#!/bin/bash

realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

CMDDIR=`dirname $0`

if [ "$#" -ne 3 ]; then
  if [ "$#" -ne 0 ]; then
    echo "Usage: $0 WWWDIR DATADIR SCRATCHDIR" >&2
    echo "   or: $0" >&2
    exit 1
  else
    WWWDIR="$CMDDIR/../.."
    DATADIR="$WWWDIR/data"
    SCRATCHDIR="$WWWDIR/scratch"
  fi
else
  WWWDIR=$1
  DATADIR=$2
  SCRATCHDIR=$3
fi

WWWDIR=`realpath "$WWWDIR"`
DATADIR=`realpath "$DATADIR"`
SCRATCHDIR=`realpath "$SCRATCHDIR"`

SITESDIR="$WWWDIR/sites"
MYSQLDIR="$DATADIR/mysql"

if ! [ -d "$SITESDIR" ]; then
  echo "Creating directory $SITESDIR"
  mkdir -p $SITESDIR
fi

if ! [ -d "$MYSQLDIR" ]; then
  echo "Creating directory $MYSQLDIR"
  mkdir -p $MYSQLDIR
fi

if ! [ -d "$SCRATCHDIR" ]; then
  echo "Creating directory $SCRATCHDIR"
  mkdir -p $SCRATCHDIR
fi

$CMDDIR/kill
echo ""

echo "Starting Docker containers:"
echo "- MariaDB:"
docker run -d --name devbox-mysql -v $MYSQLDIR:/var/lib/mysql -p 3306:3306 mixcom/devbox-mariadb-10.0
echo "- Memcached:"
docker run -d --name devbox-memcache memcached
echo "- PHP 5.6:"
docker run -d --name devbox-php -v $WWWDIR:/var/www -v $SCRATCHDIR:/var/scratch --link devbox-memcache:memcache --link devbox-mysql:mysql mixcom/devbox-php-5.6
echo "- Apache 2.4:"
docker run -d --name devbox-apache -v $WWWDIR:/var/www --link devbox-php:php -p 80:80 mixcom/devbox-apache-2.4
echo "Started all Docker containers."