#!/bin/bash

realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

CMDDIR=`dirname $0`

if [ "$#" -ne 1 ]; then
  if [ "$#" -ne 0 ]; then
    echo "Usage: $0 devboxdir" >&2
    echo "   or: $0" >&2
    exit 1
  else
    ROOTDIR="$CMDDIR/../.."
  fi
else
  ROOTDIR="$1"
fi

ROOTDIR=`realpath "$ROOTDIR"`
SITESDIR="$ROOTDIR/sites"
MYSQLDIR="$ROOTDIR/data/mysql"
WEBUIDIR="$ROOTDIR/devbox/web-ui"

if ! [ -d "$MYSQLDIR" ]; then
  echo "Creating directory $MYSQLDIR"
  mkdir -p $MYSQLDIR
fi

$CMDDIR/kill
echo ""

echo "Starting Docker containers:"
echo "- MariaDB:"
docker run -d --name devbox-mysql -v $MYSQLDIR:/var/lib/mysql -p 3306:3306 mixcom/devbox-mariadb-10.0
echo "- Memcached:"
docker run -d --name devbox-memcache memcached
echo "- PHP 5.6:"
docker run -d --name devbox-php -v $ROOTDIR:/devbox -v $WEBUIDIR:/var/www/web-ui -v $SITESDIR:/var/www/sites --link devbox-memcache:memcache --link devbox-mysql:mysql mixcom/devbox-php-5.6
docker exec devbox-php rsync -a /devbox/config/ssh-keys/ /root/.ssh
echo "- Apache 2.4:"
docker run -d --name devbox-apache -v $WEBUIDIR:/var/www/web-ui -v $SITESDIR:/var/www/sites --link devbox-php:php -p 80:80 mixcom/devbox-apache-2.4
echo "Started all Docker containers."

if [ -d "$WEBUIDIR" ]; then
  echo "Creating devbox web UI"
  git clone https://github.com/mixcom/devbox-web-ui.git "$WEBUIDIR"
  
  cd "$WEBUIDIR" && composer install --prefer-dist --no-dev --optimize-autoloader
fi

