#!/bin/bash

realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

CMDDIR=`dirname $0`

if [ "$#" -ne 1 ]; then
  if [ "$#" -ne 0 ]; then
    echo "Usage: $0 devboxdir" >&2
    echo "   or: $0" >&2
    exit 1
  else
    ROOTDIR="$CMDDIR/../.."
  fi
else
  ROOTDIR="$1"
fi

ROOTDIR=`realpath "$ROOTDIR"`
SITESDIR="$ROOTDIR/sites"
MYSQLDIR="$ROOTDIR/data/mysql"

if ! [ -d "$MYSQLDIR" ]; then
  echo "Creating directory $MYSQLDIR"
  mkdir -p $MYSQLDIR
fi

$CMDDIR/kill
echo ""

echo "Starting Docker containers:"
echo "- MariaDB:"
docker run -d --name devbox-mysql -v $MYSQLDIR:/var/lib/mysql -p 3306:3306 mixcom/devbox-mariadb-10.0
echo "- Memcached:"
docker run -d --name devbox-memcache memcached
echo "- PHP 5.6:"
docker run -d --name devbox-php -v $ROOTDIR:/devbox -v $SITESDIR:/var/www/sites --link devbox-memcache:memcache --link devbox-mysql:mysql mixcom/devbox-php-5.6
echo "- Apache 2.4:"
docker run -d --name devbox-apache -v $ROOTDIR:/var/www --link devbox-php:php -p 80:80 mixcom/devbox-apache-2.4
echo "- phpMyAdmin:"
docker run -d --name devbox-phpmyadmin -p 8081:443 --link devbox-mysql:mysql marvambass/phpmyadmin
echo "Started all Docker containers."
echo "Devbox is up and running."