parameters:
  application.name: DEVBOT
  application.version: 0.1

services:
  application:
    class: Symfony\Component\Console\Application
    arguments: ["%application.name%", "%application.version%"]
    calls:
      - [add, ["@site.command.clone"]]
      - [add, ["@site.command.install"]]
      - [add, ["@site.command.archive"]]
      - [add, ["@site.command.setup"]]
      
  site.command.clone:
    class: Devbot\Site\Console\Command\CloneCommand
    calls:
      - [setCloner, ["@site.clone.gitCloner"]]
    
  site.clone.gitCloner:
    class: Devbot\Site\VcsClone\GitCloner
  
  site.command.install:
    class: Devbot\Site\Console\Command\InstallCommand
    calls:
      - [setInstaller, ["@site.installer"]]
  
  site.command.archive:
    class: Devbot\Site\Console\Command\ArchiveCommand
    calls:
      - [setInstaller, ["@site.installer"]]
  
  site.command.setup:
    class: Devbot\Site\Console\Command\SetupCommand
    calls:
      - [setCloner, ["@site.clone.gitCloner"]]
      - [setInstaller, ["@site.installer"]]
  
  site.installer:
    class: Devbot\Site\Install\SiteInstaller
    calls:
      - [setArchiveCompressor, ["@site.install.archiveCompressor"]]
      - [addPlugin, ["@site.install.publicSymlink"]]
      - [addPlugin, ["@site.install.htaccessTemplate"]]
      - [addPlugin, ["@drupal.install.files"]]
  
  site.install.publicSymlink:
    class: Devbot\Site\Install\Plugin\PublicSymlink
  
  site.install.htaccessTemplate:
    class: Devbot\Site\Install\Plugin\HtaccessTemplate
  
  site.install.archiveCompressor:
    class: Devbot\Install\ArchiveZipCompressor
    
  drupal.install.files:
    class: Devbot\Plugin\Drupal\Install\Plugin\Files

