parameters:
  application.name: DEVBOT
  application.version: 0.1

services:
  application:
    class: Symfony\Component\Console\Application
    arguments: ["%application.name%", "%application.version%"]
    calls:
      - [add, ["@site.command.clone"]]
      - [add, ["@site.command.install"]]
      - [add, ["@site.command.setup"]]
      
  site.command.clone:
    class: Devbot\Plugins\Site\Console\Command\CloneCommand
    arguments: ["@site.task.gitClone"]
    
  site.task.gitClone:
    class: Devbot\Plugins\Site\Task\GitCloneTask
  
  site.command.install:
    class: Devbot\Plugins\Site\Console\Command\InstallCommand
    arguments: ["@site.task.install"]
    
  site.task.install:
    class: Devbot\Plugins\Site\Task\InstallTask
  
  site.command.setup:
    class: Devbot\Plugins\Site\Console\Command\SetupCommand
    arguments: ["@site.task.setup"]
    
  site.task.setup:
    class: Devbot\Plugins\Site\Task\SetupTask
    calls:
      - [setGitCloneTask, ["@site.task.gitClone"]]
      - [setInstallTask, ["@site.task.install"]]
  
  drupal.installer.db:
    class: Devbot\Plugins\Drupal\Installer\DbInstaller

